// Aureon Language — Full Lexicon (1000+ words)
const lexicon = [
  // ── NATURE ──────────────────────────────────────────────────────────────
  { word: "vorael", pos: "Noun", meaning: "Sun" },
  { word: "thiveln", pos: "Noun", meaning: "Water" },
  { word: "caendor", pos: "Noun", meaning: "Mountain" },
  { word: "uviraek", pos: "Noun", meaning: "Fire" },
  { word: "solmeth", pos: "Noun", meaning: "Wind" },
  { word: "dravenil", pos: "Noun", meaning: "Tree" },
  { word: "quelithar", pos: "Noun", meaning: "Stone" },
  { word: "faerond", pos: "Noun", meaning: "Sky" },
  { word: "ilduvok", pos: "Noun", meaning: "Sea" },
  { word: "threnox", pos: "Noun", meaning: "Soil / Earth" },
  { word: "olvaren", pos: "Noun", meaning: "Moon" },
  { word: "zephkion", pos: "Noun", meaning: "Star" },
  { word: "brumathal", pos: "Noun", meaning: "Cloud" },
  { word: "oriveld", pos: "Noun", meaning: "Rain" },
  { word: "galnethor", pos: "Noun", meaning: "Snow" },
  { word: "yuvraek", pos: "Noun", meaning: "Ice" },
  { word: "draemoliv", pos: "Noun", meaning: "Flower" },
  { word: "sevionath", pos: "Noun", meaning: "Leaf" },
  { word: "corvelith", pos: "Noun", meaning: "Root" },
  { word: "thuriaen", pos: "Noun", meaning: "Seed" },
  { word: "elvornath", pos: "Noun", meaning: "Fruit" },
  { word: "nithaelon", pos: "Noun", meaning: "River" },
  { word: "quelvaren", pos: "Noun", meaning: "Lake" },
  { word: "orventh", pos: "Noun", meaning: "Cave" },
  { word: "salmireth", pos: "Noun", meaning: "Desert" },
  { word: "fendraxon", pos: "Noun", meaning: "Forest" },
  { word: "vaelunith", pos: "Noun", meaning: "Island" },
  { word: "throvalon", pos: "Noun", meaning: "Valley" },
  { word: "caeldunath", pos: "Noun", meaning: "Cliff" },
  { word: "mornithelon", pos: "Noun", meaning: "Fog" },
  { word: "brevaelon", pos: "Noun", meaning: "Dawn" },
  { word: "solkethiv", pos: "Noun", meaning: "Dusk" },
  { word: "veldronis", pos: "Noun", meaning: "Night" },
  { word: "auremnil", pos: "Noun", meaning: "Day" },
  { word: "thyronaeth", pos: "Noun", meaning: "Year" },
  { word: "fenvalis", pos: "Noun", meaning: "Season" },
  { word: "uldrathen", pos: "Noun", meaning: "Spring" },
  { word: "caervonith", pos: "Noun", meaning: "Summer" },
  { word: "melvithar", pos: "Noun", meaning: "Autumn" },
  { word: "drothynael", pos: "Noun", meaning: "Winter" },
  { word: "voraelik", pos: "Noun", meaning: "Horizon" },
  { word: "thimralven", pos: "Noun", meaning: "Tide" },
  { word: "caeldrixoth", pos: "Noun", meaning: "Echo" },
  { word: "uvithaelorn", pos: "Noun", meaning: "Flame" },
  { word: "solmethixal", pos: "Noun", meaning: "Whisper" },
  { word: "drenvorneth", pos: "Noun", meaning: "Thunder" },
  { word: "quelvorilond", pos: "Noun", meaning: "Lightning" },
  { word: "faerathorex", pos: "Noun", meaning: "Rainbow" },
  { word: "ildrakonen", pos: "Noun", meaning: "Mist" },
  { word: "thornvaexith", pos: "Noun", meaning: "Dust" },
  { word: "vornethil", pos: "Noun", meaning: "Tornado" },
  { word: "threkaveld", pos: "Noun", meaning: "Glacier" },
  { word: "quelonvath", pos: "Noun", meaning: "Swamp" },
  { word: "dravekithor", pos: "Noun", meaning: "Jungle" },
  { word: "ilvaenoth", pos: "Noun", meaning: "Tundra" },
  { word: "solvaekith", pos: "Noun", meaning: "Prairie" },
  { word: "faeruveld", pos: "Noun", meaning: "Meadow" },
  { word: "threnivael", pos: "Noun", meaning: "Marsh" },
  { word: "orvaksel", pos: "Noun", meaning: "Ravine" },
  { word: "caldvonith", pos: "Noun", meaning: "Canyon" },
  { word: "meldrivael", pos: "Noun", meaning: "Waterfall" },
  { word: "quelvoreth", pos: "Noun", meaning: "Spring (water)" },
  { word: "druvanthek", pos: "Noun", meaning: "Geyser" },
  { word: "solmirael", pos: "Noun", meaning: "Comet" },
  { word: "faevronith", pos: "Noun", meaning: "Eclipse" },
  { word: "thalvexond", pos: "Noun", meaning: "Aurora" },
  { word: "yuvnethilor", pos: "Noun", meaning: "Meteor" },
  { word: "brevonvael", pos: "Noun", meaning: "Dew" },
  { word: "quelitherond", pos: "Noun", meaning: "Pebble" },
  { word: "ornivaeth", pos: "Noun", meaning: "Soil (fertile)" },
  { word: "drenthikal", pos: "Noun", meaning: "Lava" },
  { word: "solvaexorn", pos: "Noun", meaning: "Ash" },
  { word: "thalvondrith", pos: "Noun", meaning: "Ember" },
  { word: "queldruvaith", pos: "Noun", meaning: "Smoke" },
  { word: "ilvorneth", pos: "Noun", meaning: "Petal" },
  { word: "brevithalon", pos: "Noun", meaning: "Blossom" },
  { word: "caldorvenil", pos: "Noun", meaning: "Bark (tree)" },
  { word: "thornivaelon", pos: "Noun", meaning: "Thorn" },
  { word: "dravenilokon", pos: "Noun", meaning: "Branch" },
  { word: "vornithek", pos: "Noun", meaning: "Moss" },
  { word: "quelvaelith", pos: "Noun", meaning: "Reed" },
  { word: "ildruvond", pos: "Noun", meaning: "Fern" },
  { word: "solvaekorith", pos: "Noun", meaning: "Vine" },

  // ── ANIMALS ─────────────────────────────────────────────────────────────
  { word: "vurkaelon", pos: "Noun", meaning: "Wolf" },
  { word: "thivronath", pos: "Noun", meaning: "Eagle" },
  { word: "quelmarev", pos: "Noun", meaning: "Deer" },
  { word: "orvithek", pos: "Noun", meaning: "Fish" },
  { word: "caeldrakis", pos: "Noun", meaning: "Serpent" },
  { word: "yuvmirak", pos: "Noun", meaning: "Bear" },
  { word: "selnothar", pos: "Noun", meaning: "Fox" },
  { word: "brevkinel", pos: "Noun", meaning: "Rabbit" },
  { word: "drumathok", pos: "Noun", meaning: "Horse" },
  { word: "thornvelis", pos: "Noun", meaning: "Cat" },
  { word: "dravexonil", pos: "Noun", meaning: "Dog" },
  { word: "ilvornaketh", pos: "Noun", meaning: "Bird" },
  { word: "queldravith", pos: "Noun", meaning: "Crow" },
  { word: "solmithrok", pos: "Noun", meaning: "Owl" },
  { word: "faervonith", pos: "Noun", meaning: "Hawk" },
  { word: "threnvalok", pos: "Noun", meaning: "Raven" },
  { word: "caldriveth", pos: "Noun", meaning: "Swan" },
  { word: "meldravik", pos: "Noun", meaning: "Heron" },
  { word: "quelvonak", pos: "Noun", meaning: "Frog" },
  { word: "drenthivael", pos: "Noun", meaning: "Turtle" },
  { word: "solvrathek", pos: "Noun", meaning: "Crab" },
  { word: "ilvakendor", pos: "Noun", meaning: "Spider" },
  { word: "vurnelidok", pos: "Noun", meaning: "Ant" },
  { word: "thalvronek", pos: "Noun", meaning: "Bee" },
  { word: "brevondrath", pos: "Noun", meaning: "Butterfly" },
  { word: "quelvornik", pos: "Noun", meaning: "Moth" },
  { word: "drenvokith", pos: "Noun", meaning: "Worm" },
  { word: "solmekthor", pos: "Noun", meaning: "Beetle" },
  { word: "faeldruvok", pos: "Noun", meaning: "Rat" },
  { word: "thivakeln", pos: "Noun", meaning: "Mouse" },
  { word: "caldrivorn", pos: "Noun", meaning: "Lion" },
  { word: "meldrovik", pos: "Noun", meaning: "Tiger" },
  { word: "quelondrith", pos: "Noun", meaning: "Leopard" },
  { word: "vurvakhond", pos: "Noun", meaning: "Elk" },
  { word: "dravathek", pos: "Noun", meaning: "Boar" },
  { word: "ilvornaek", pos: "Noun", meaning: "Otter" },
  { word: "brevornivak", pos: "Noun", meaning: "Badger" },
  { word: "quelthivorn", pos: "Noun", meaning: "Hawk (night)" },
  { word: "thaldruvith", pos: "Noun", meaning: "Whale" },
  { word: "solnivaek", pos: "Noun", meaning: "Dolphin" },
  { word: "faevronaek", pos: "Noun", meaning: "Shark" },
  { word: "drenivokith", pos: "Noun", meaning: "Octopus" },
  { word: "ilvaekorn", pos: "Noun", meaning: "Jellyfish" },
  { word: "vurthekond", pos: "Noun", meaning: "Crocodile" },
  { word: "queldrakov", pos: "Noun", meaning: "Dragon" },
  { word: "thalorniveth", pos: "Noun", meaning: "Phoenix" },
  { word: "brevakildor", pos: "Noun", meaning: "Griffin" },
  { word: "solvendrithok", pos: "Noun", meaning: "Unicorn" },

  // ── PEOPLE / SOCIETY ─────────────────────────────────────────────────────
  { word: "aelvorith", pos: "Noun", meaning: "Person" },
  { word: "threndalon", pos: "Noun", meaning: "Child" },
  { word: "quelorneth", pos: "Noun", meaning: "Elder" },
  { word: "vurmethis", pos: "Noun", meaning: "Warrior" },
  { word: "solvaneith", pos: "Noun", meaning: "Healer" },
  { word: "faendrixal", pos: "Noun", meaning: "Merchant" },
  { word: "ildrakoth", pos: "Noun", meaning: "Scholar" },
  { word: "caervelith", pos: "Noun", meaning: "King" },
  { word: "mornaeliv", pos: "Noun", meaning: "Queen" },
  { word: "brevithon", pos: "Noun", meaning: "Friend" },
  { word: "threnivok", pos: "Noun", meaning: "Stranger" },
  { word: "quelvarend", pos: "Noun", meaning: "Ally" },
  { word: "orvandrak", pos: "Noun", meaning: "Enemy" },
  { word: "caldvorim", pos: "Noun", meaning: "Leader" },
  { word: "meldrivath", pos: "Noun", meaning: "Servant" },
  { word: "solmaekith", pos: "Noun", meaning: "Farmer" },
  { word: "faerondvik", pos: "Noun", meaning: "Fisher" },
  { word: "drenvaelith", pos: "Noun", meaning: "Hunter" },
  { word: "ilvormaek", pos: "Noun", meaning: "Craftsman" },
  { word: "brevondrith", pos: "Noun", meaning: "Builder" },
  { word: "quelthivorn", pos: "Noun", meaning: "Sailor" },
  { word: "vuraelindok", pos: "Noun", meaning: "Guard" },
  { word: "thalvorinak", pos: "Noun", meaning: "Spy" },
  { word: "soldruvirath", pos: "Noun", meaning: "Assassin" },
  { word: "faelvronith", pos: "Noun", meaning: "Thief" },
  { word: "drenthakov", pos: "Noun", meaning: "Priest" },
  { word: "ilvornathek", pos: "Noun", meaning: "Witch" },
  { word: "quelvaelond", pos: "Noun", meaning: "Wizard" },
  { word: "vurmithelon", pos: "Noun", meaning: "Knight" },
  { word: "thaldruvael", pos: "Noun", meaning: "General" },
  { word: "brevornivek", pos: "Noun", meaning: "Prince" },
  { word: "solvakendor", pos: "Noun", meaning: "Princess" },
  { word: "faevronthak", pos: "Noun", meaning: "Duke" },
  { word: "drenvaelixor", pos: "Noun", meaning: "Duchess" },
  { word: "ildvornith", pos: "Noun", meaning: "Ambassador" },
  { word: "quelvormaek", pos: "Noun", meaning: "Judge" },
  { word: "vurthakond", pos: "Noun", meaning: "Prisoner" },
  { word: "thalvenaek", pos: "Noun", meaning: "Refugee" },
  { word: "solvornith", pos: "Noun", meaning: "Orphan" },
  { word: "brevithakon", pos: "Noun", meaning: "Widow" },
  { word: "caldruvenil", pos: "Noun", meaning: "Ancestor" },
  { word: "meldrakivon", pos: "Noun", meaning: "Descendant" },
  { word: "quelornixa", pos: "Noun", meaning: "Twin" },
  { word: "drenvaketh", pos: "Noun", meaning: "Parent" },
  { word: "ilvornaeth", pos: "Noun", meaning: "Mother" },
  { word: "solmaekorn", pos: "Noun", meaning: "Father" },
  { word: "faerathon", pos: "Noun", meaning: "Sister" },
  { word: "thalvornikaek", pos: "Noun", meaning: "Brother" },
  { word: "brevondrivak", pos: "Noun", meaning: "Cousin" },
  { word: "queldruxith", pos: "Noun", meaning: "Uncle" },
  { word: "vurnaelith", pos: "Noun", meaning: "Aunt" },

  // ── STRUCTURES / PLACES ──────────────────────────────────────────────────
  { word: "vurmithon", pos: "Noun", meaning: "Sword" },
  { word: "caldrunath", pos: "Noun", meaning: "Armor" },
  { word: "selmothix", pos: "Noun", meaning: "Crown" },
  { word: "drenvaelithe", pos: "Noun", meaning: "Throne" },
  { word: "yuvornithen", pos: "Noun", meaning: "Castle" },
  { word: "solmiraeld", pos: "Noun", meaning: "Tower" },
  { word: "faevraelith", pos: "Noun", meaning: "Bridge" },
  { word: "thornvaelond", pos: "Noun", meaning: "Road" },
  { word: "meldruvik", pos: "Noun", meaning: "Village" },
  { word: "caelvorith", pos: "Noun", meaning: "City" },
  { word: "brevakenth", pos: "Noun", meaning: "Market" },
  { word: "uldmirenix", pos: "Noun", meaning: "Temple" },
  { word: "threnovalith", pos: "Noun", meaning: "Library" },
  { word: "quelvaenith", pos: "Noun", meaning: "Garden" },
  { word: "orveldrumath", pos: "Noun", meaning: "Forge" },
  { word: "salmaetha", pos: "Noun", meaning: "Ship" },
  { word: "brevithalith", pos: "Noun", meaning: "Scroll" },
  { word: "thalvondrix", pos: "Noun", meaning: "Inn" },
  { word: "quelvorexith", pos: "Noun", meaning: "Tavern" },
  { word: "drenvaekond", pos: "Noun", meaning: "Dungeon" },
  { word: "ilvornithek", pos: "Noun", meaning: "Arena" },
  { word: "solmaekorn", pos: "Noun", meaning: "Barracks" },
  { word: "faervondrix", pos: "Noun", meaning: "Harbor" },
  { word: "thalvronaek", pos: "Noun", meaning: "Dock" },
  { word: "brevornikaek", pos: "Noun", meaning: "Warehouse" },
  { word: "queldruvond", pos: "Noun", meaning: "Blacksmith" },
  { word: "vurnethikal", pos: "Noun", meaning: "Bakery" },
  { word: "solvaendrik", pos: "Noun", meaning: "Apothecary" },
  { word: "faeldruvith", pos: "Noun", meaning: "Academy" },
  { word: "drenthivael", pos: "Noun", meaning: "Palace" },
  { word: "ilvorvaeth", pos: "Noun", meaning: "Shrine" },
  { word: "caldvornek", pos: "Noun", meaning: "Tomb" },
  { word: "meldrivonth", pos: "Noun", meaning: "Cemetery" },
  { word: "quelornixa", pos: "Noun", meaning: "Lighthouse" },
  { word: "vurthivond", pos: "Noun", meaning: "Watchtower" },
  { word: "thalvorindok", pos: "Noun", meaning: "Gate" },
  { word: "brevakithor", pos: "Noun", meaning: "Wall" },
  { word: "quelvaenok", pos: "Noun", meaning: "Alley" },
  { word: "drenvaexith", pos: "Noun", meaning: "Plaza" },
  { word: "ilvornivak", pos: "Noun", meaning: "Courtyard" },

  // ── ABSTRACT / EMOTIONS ──────────────────────────────────────────────────
  { word: "voraenth", pos: "Noun", meaning: "Light" },
  { word: "thimraken", pos: "Noun", meaning: "Shadow" },
  { word: "caeldorith", pos: "Noun", meaning: "Hope" },
  { word: "uvithalend", pos: "Noun", meaning: "Despair" },
  { word: "solmerith", pos: "Noun", meaning: "Courage" },
  { word: "drenvithaeld", pos: "Noun", meaning: "Honor" },
  { word: "quelvorith", pos: "Noun", meaning: "Truth" },
  { word: "faerathorix", pos: "Noun", meaning: "Beauty" },
  { word: "ildmethon", pos: "Noun", meaning: "Fear" },
  { word: "thornaelix", pos: "Noun", meaning: "Memory" },
  { word: "meldrakond", pos: "Noun", meaning: "Joy" },
  { word: "caervindrak", pos: "Noun", meaning: "Sorrow" },
  { word: "brevornith", pos: "Noun", meaning: "Peace" },
  { word: "uldvarael", pos: "Noun", meaning: "War" },
  { word: "thalvornixa", pos: "Noun", meaning: "Justice" },
  { word: "quelithenoth", pos: "Noun", meaning: "Mercy" },
  { word: "orveldraki", pos: "Noun", meaning: "Power" },
  { word: "salmirenth", pos: "Noun", meaning: "Knowledge" },
  { word: "faevithalon", pos: "Noun", meaning: "Music" },
  { word: "drenmethixal", pos: "Noun", meaning: "Silence" },
  { word: "meldrakona", pos: "Noun", meaning: "Anger" },
  { word: "caervindral", pos: "Noun", meaning: "Surprise" },
  { word: "brevornell", pos: "Noun", meaning: "Excitement" },
  { word: "uldvaraex", pos: "Noun", meaning: "Anxiety" },
  { word: "thalvornelos", pos: "Noun", meaning: "Confidence" },
  { word: "quelithenos", pos: "Noun", meaning: "Loneliness" },
  { word: "orveldraken", pos: "Noun", meaning: "Gratitude" },
  { word: "salmaethix", pos: "Noun", meaning: "Curiosity" },
  { word: "faevithalond", pos: "Noun", meaning: "Pride" },
  { word: "drenmethora", pos: "Noun", meaning: "Shame" },
  { word: "vornithael", pos: "Noun", meaning: "Love" },
  { word: "quelondrax", pos: "Noun", meaning: "Hatred" },
  { word: "thalvornixek", pos: "Noun", meaning: "Envy" },
  { word: "solmekaenth", pos: "Noun", meaning: "Greed" },
  { word: "faelvorith", pos: "Noun", meaning: "Lust" },
  { word: "drenvorath", pos: "Noun", meaning: "Sloth" },
  { word: "ilvornixal", pos: "Noun", meaning: "Wrath" },
  { word: "queldruvinak", pos: "Noun", meaning: "Gluttony" },
  { word: "vurnaelthek", pos: "Noun", meaning: "Virtue" },
  { word: "thalvorindrak", pos: "Noun", meaning: "Sin" },
  { word: "brevakildrak", pos: "Noun", meaning: "Faith" },
  { word: "quelornivak", pos: "Noun", meaning: "Doubt" },
  { word: "solvaendrek", pos: "Noun", meaning: "Wisdom" },
  { word: "faevithorix", pos: "Noun", meaning: "Folly" },
  { word: "drenvornixak", pos: "Noun", meaning: "Patience" },
  { word: "ilvakendrel", pos: "Noun", meaning: "Rage" },
  { word: "quelvorinath", pos: "Noun", meaning: "Calm" },
  { word: "vurthakindel", pos: "Noun", meaning: "Dread" },
  { word: "thalvaenixon", pos: "Noun", meaning: "Wonder" },
  { word: "brevornithek", pos: "Noun", meaning: "Awe" },
  { word: "queldruvixal", pos: "Noun", meaning: "Bliss" },
  { word: "solmirexond", pos: "Noun", meaning: "Melancholy" },
  { word: "faervaelith", pos: "Noun", meaning: "Nostalgia" },
  { word: "drenvaekorn", pos: "Noun", meaning: "Yearning" },
  { word: "ilvornixel", pos: "Noun", meaning: "Ecstasy" },
  { word: "quelthivond", pos: "Noun", meaning: "Serenity" },

  // ── BODY PARTS ──────────────────────────────────────────────────────────
  { word: "voraevith", pos: "Noun", meaning: "Eye" },
  { word: "thimralthe", pos: "Noun", meaning: "Ear" },
  { word: "caeldrixon", pos: "Noun", meaning: "Hand" },
  { word: "uvithaeliv", pos: "Noun", meaning: "Foot" },
  { word: "solmethixor", pos: "Noun", meaning: "Mouth" },
  { word: "drenvorniv", pos: "Noun", meaning: "Nose" },
  { word: "quelvorilath", pos: "Noun", meaning: "Head" },
  { word: "faerathoril", pos: "Noun", meaning: "Heart" },
  { word: "ildrakoren", pos: "Noun", meaning: "Back" },
  { word: "thornvaexal", pos: "Noun", meaning: "Arm" },
  { word: "voraelith", pos: "Noun", meaning: "Leg" },
  { word: "thivelnath", pos: "Noun", meaning: "Finger" },
  { word: "caendoriv", pos: "Noun", meaning: "Tooth" },
  { word: "uviraekond", pos: "Noun", meaning: "Tongue" },
  { word: "solmethend", pos: "Noun", meaning: "Breath" },
  { word: "brevornivak", pos: "Noun", meaning: "Shoulder" },
  { word: "quelvorixal", pos: "Noun", meaning: "Knee" },
  { word: "drenvaekith", pos: "Noun", meaning: "Elbow" },
  { word: "ilvornivek", pos: "Noun", meaning: "Wrist" },
  { word: "solmaekivon", pos: "Noun", meaning: "Ankle" },
  { word: "faerondivak", pos: "Noun", meaning: "Hip" },
  { word: "thalvornek", pos: "Noun", meaning: "Chest" },
  { word: "brevakinthor", pos: "Noun", meaning: "Belly" },
  { word: "quelornivoth", pos: "Noun", meaning: "Neck" },
  { word: "vurnaelixon", pos: "Noun", meaning: "Chin" },
  { word: "drenvaelixon", pos: "Noun", meaning: "Cheek" },
  { word: "ilvakendorth", pos: "Noun", meaning: "Forehead" },
  { word: "queldruvixon", pos: "Noun", meaning: "Jaw" },
  { word: "solmiraexal", pos: "Noun", meaning: "Thumb" },
  { word: "faevronithak", pos: "Noun", meaning: "Toe" },
  { word: "thalvondraxil", pos: "Noun", meaning: "Spine" },
  { word: "brevorinaek", pos: "Noun", meaning: "Rib" },
  { word: "quelvaenixal", pos: "Noun", meaning: "Skull" },
  { word: "drenivokond", pos: "Noun", meaning: "Blood" },
  { word: "ilvornivon", pos: "Noun", meaning: "Bone" },
  { word: "solvaekilvon", pos: "Noun", meaning: "Skin" },
  { word: "faervonithon", pos: "Noun", meaning: "Hair" },
  { word: "thalvoraxek", pos: "Noun", meaning: "Nail (finger)" },
  { word: "brevonivith", pos: "Noun", meaning: "Lung" },
  { word: "quelvoraxond", pos: "Noun", meaning: "Liver" },
  { word: "drenvakixor", pos: "Noun", meaning: "Kidney" },
  { word: "ilvakendron", pos: "Noun", meaning: "Brain" },

  // ── FOOD / DRINK ─────────────────────────────────────────────────────────
  { word: "meldroneth", pos: "Noun", meaning: "Bread" },
  { word: "caervinalith", pos: "Noun", meaning: "Meat" },
  { word: "brevakendral", pos: "Noun", meaning: "Herb" },
  { word: "uldmirithex", pos: "Noun", meaning: "Honey" },
  { word: "thalvorenax", pos: "Noun", meaning: "Salt" },
  { word: "quelithendor", pos: "Noun", meaning: "Grain" },
  { word: "orveldruxith", pos: "Noun", meaning: "Mushroom" },
  { word: "salmirexond", pos: "Noun", meaning: "Berry" },
  { word: "faevitharxen", pos: "Noun", meaning: "Nut" },
  { word: "drenmethoxal", pos: "Noun", meaning: "Root vegetable" },
  { word: "vurnaelixak", pos: "Noun", meaning: "Soup" },
  { word: "thalvondrix", pos: "Noun", meaning: "Stew" },
  { word: "brevakindoth", pos: "Noun", meaning: "Porridge" },
  { word: "quelornivak", pos: "Noun", meaning: "Cheese" },
  { word: "drenvakixal", pos: "Noun", meaning: "Butter" },
  { word: "ilvorniveth", pos: "Noun", meaning: "Egg" },
  { word: "solmaekixon", pos: "Noun", meaning: "Milk" },
  { word: "faervonithon", pos: "Noun", meaning: "Wine" },
  { word: "thalvoraxek", pos: "Noun", meaning: "Ale" },
  { word: "brevondrithak", pos: "Noun", meaning: "Mead" },
  { word: "quelvaenixoth", pos: "Noun", meaning: "Tea" },
  { word: "drenivokivak", pos: "Noun", meaning: "Broth" },
  { word: "ilvornivon", pos: "Noun", meaning: "Cake" },
  { word: "solvaekilvak", pos: "Noun", meaning: "Pie" },
  { word: "faervonivak", pos: "Noun", meaning: "Roast" },
  { word: "thalvoraxil", pos: "Noun", meaning: "Pickle" },
  { word: "brevonivaek", pos: "Noun", meaning: "Jam" },
  { word: "quelvoraxon", pos: "Noun", meaning: "Sauce" },
  { word: "drenvakixoth", pos: "Noun", meaning: "Spice" },
  { word: "ilvakendrixal", pos: "Noun", meaning: "Pepper" },

  // ── MATERIALS ────────────────────────────────────────────────────────────
  { word: "thalvorenaxil", pos: "Noun", meaning: "Iron" },
  { word: "quelithendar", pos: "Noun", meaning: "Gold" },
  { word: "orveldruxithe", pos: "Noun", meaning: "Silver" },
  { word: "faevitharxeld", pos: "Noun", meaning: "Ivory" },
  { word: "drenmethoxen", pos: "Noun", meaning: "Coal" },
  { word: "vurnelixond", pos: "Noun", meaning: "Copper" },
  { word: "thalvondrixak", pos: "Noun", meaning: "Bronze" },
  { word: "brevakindrak", pos: "Noun", meaning: "Steel" },
  { word: "quelorniveth", pos: "Noun", meaning: "Crystal" },
  { word: "drenvakixond", pos: "Noun", meaning: "Obsidian" },
  { word: "ilvornivak", pos: "Noun", meaning: "Marble" },
  { word: "solmaekixal", pos: "Noun", meaning: "Clay" },
  { word: "faervonithek", pos: "Noun", meaning: "Glass" },
  { word: "thalvoraxond", pos: "Noun", meaning: "Leather" },
  { word: "brevondrithek", pos: "Noun", meaning: "Cloth" },
  { word: "quelvaenixok", pos: "Noun", meaning: "Silk" },
  { word: "drenivokixal", pos: "Noun", meaning: "Wool" },
  { word: "ilvornivonak", pos: "Noun", meaning: "Cotton" },
  { word: "solvaekilvek", pos: "Noun", meaning: "Linen" },
  { word: "faervonivek", pos: "Noun", meaning: "Amber" },
  { word: "thalvoraxith", pos: "Noun", meaning: "Pearl" },
  { word: "brevonivoth", pos: "Noun", meaning: "Ruby" },
  { word: "quelvoraxek", pos: "Noun", meaning: "Sapphire" },
  { word: "drenvakixon", pos: "Noun", meaning: "Emerald" },
  { word: "ilvakendrixond", pos: "Noun", meaning: "Diamond" },

  // ── TIME ─────────────────────────────────────────────────────────────────
  { word: "voraenil", pos: "Noun", meaning: "Morning" },
  { word: "thimranel", pos: "Noun", meaning: "Afternoon" },
  { word: "caeldorixa", pos: "Noun", meaning: "Evening" },
  { word: "uvithalend", pos: "Noun", meaning: "Midnight" },
  { word: "solmeritha", pos: "Noun", meaning: "Hour" },
  { word: "drenvithor", pos: "Noun", meaning: "Minute" },
  { word: "quelvorix", pos: "Noun", meaning: "Second" },
  { word: "faerathor", pos: "Noun", meaning: "Week" },
  { word: "ildmethorn", pos: "Noun", meaning: "Month" },
  { word: "thornaelond", pos: "Noun", meaning: "Century" },
  { word: "vornaelikond", pos: "Noun", meaning: "Decade" },
  { word: "threnivakond", pos: "Noun", meaning: "Millennium" },
  { word: "quelvoraxon", pos: "Noun", meaning: "Moment" },
  { word: "drenvaelixak", pos: "Noun", meaning: "Era" },
  { word: "ilvornivakith", pos: "Noun", meaning: "Epoch" },
  { word: "solmaekixoth", pos: "Noun", meaning: "Yesterday" },
  { word: "faervonithond", pos: "Noun", meaning: "Tomorrow" },
  { word: "thalvoraxivak", pos: "Noun", meaning: "Future" },
  { word: "brevondrithond", pos: "Noun", meaning: "Past" },
  { word: "quelvaenixiv", pos: "Noun", meaning: "Present" },

  // ── WEAPONS / COMBAT ────────────────────────────────────────────────────
  { word: "vurmithon", pos: "Noun", meaning: "Sword" },
  { word: "thivaelon", pos: "Noun", meaning: "Shield" },
  { word: "queldrakis", pos: "Noun", meaning: "Bow" },
  { word: "orvithaeld", pos: "Noun", meaning: "Spear" },
  { word: "brevakithorn", pos: "Noun", meaning: "Axe" },
  { word: "quelornivixal", pos: "Noun", meaning: "Dagger" },
  { word: "drenvakivak", pos: "Noun", meaning: "Mace" },
  { word: "ilvornivixal", pos: "Noun", meaning: "Crossbow" },
  { word: "solmaekivon", pos: "Noun", meaning: "Arrow" },
  { word: "faervonivak", pos: "Noun", meaning: "Bolt" },
  { word: "thalvoraxivak", pos: "Noun", meaning: "Catapult" },
  { word: "brevonivaekith", pos: "Noun", meaning: "Siege engine" },
  { word: "quelvoraxivith", pos: "Noun", meaning: "Flail" },
  { word: "drenvaekivoth", pos: "Noun", meaning: "Staff (weapon)" },
  { word: "ilvakendrixiv", pos: "Noun", meaning: "Whip" },

  // ── NUMBERS ──────────────────────────────────────────────────────────────
  { word: "vorae", pos: "Number", meaning: "One" },
  { word: "thimen", pos: "Number", meaning: "Two" },
  { word: "quelda", pos: "Number", meaning: "Three" },
  { word: "orvik", pos: "Number", meaning: "Four" },
  { word: "caldur", pos: "Number", meaning: "Five" },
  { word: "selmon", pos: "Number", meaning: "Six" },
  { word: "drenval", pos: "Number", meaning: "Seven" },
  { word: "yuvrek", pos: "Number", meaning: "Eight" },
  { word: "solmae", pos: "Number", meaning: "Nine" },
  { word: "faevith", pos: "Number", meaning: "Ten" },
  { word: "voraethimen", pos: "Number", meaning: "Eleven" },
  { word: "thimendael", pos: "Number", meaning: "Twenty" },
  { word: "caldurvael", pos: "Number", meaning: "Fifty" },
  { word: "faevithvorn", pos: "Number", meaning: "Hundred" },
  { word: "queldarivond", pos: "Number", meaning: "Thousand" },

  // ── ADJECTIVES ───────────────────────────────────────────────────────────
  { word: "vurmaeth", pos: "Adjective", meaning: "Red" },
  { word: "thiventh", pos: "Adjective", meaning: "Blue" },
  { word: "quelvarith", pos: "Adjective", meaning: "Green" },
  { word: "orviken", pos: "Adjective", meaning: "Yellow" },
  { word: "caldrumith", pos: "Adjective", meaning: "Orange" },
  { word: "selmiren", pos: "Adjective", meaning: "Purple" },
  { word: "drenvalix", pos: "Adjective", meaning: "White" },
  { word: "yuvornaeth", pos: "Adjective", meaning: "Black" },
  { word: "solmaevith", pos: "Adjective", meaning: "Grey" },
  { word: "faerathun", pos: "Adjective", meaning: "Brown" },
  { word: "voraen", pos: "Adjective", meaning: "Bright" },
  { word: "thimrak", pos: "Adjective", meaning: "Cold" },
  { word: "caeldorak", pos: "Adjective", meaning: "Tall" },
  { word: "uvithaeld", pos: "Adjective", meaning: "Hot" },
  { word: "solmeriv", pos: "Adjective", meaning: "Fast" },
  { word: "drenvithael", pos: "Adjective", meaning: "Strong" },
  { word: "quelvornixa", pos: "Adjective", meaning: "Wise" },
  { word: "faerathen", pos: "Adjective", meaning: "Beautiful" },
  { word: "ildmethak", pos: "Adjective", meaning: "Dark" },
  { word: "thornaelon", pos: "Adjective", meaning: "Ancient" },
  { word: "meldrakiv", pos: "Adjective", meaning: "Small" },
  { word: "caervinath", pos: "Adjective", meaning: "Large" },
  { word: "brevornath", pos: "Adjective", meaning: "Happy" },
  { word: "uldvarith", pos: "Adjective", meaning: "Sad" },
  { word: "thalvornil", pos: "Adjective", meaning: "Brave" },
  { word: "quelithend", pos: "Adjective", meaning: "Kind" },
  { word: "orveldrak", pos: "Adjective", meaning: "Cruel" },
  { word: "salmiren", pos: "Adjective", meaning: "Silent" },
  { word: "faevithald", pos: "Adjective", meaning: "Loud" },
  { word: "drenmethiv", pos: "Adjective", meaning: "Sharp" },
  { word: "vurmaetha", pos: "Adjective", meaning: "Hollow" },
  { word: "thivelniv", pos: "Adjective", meaning: "Smooth" },
  { word: "caendorix", pos: "Adjective", meaning: "Rough" },
  { word: "uviraekil", pos: "Adjective", meaning: "Dry" },
  { word: "solmethal", pos: "Adjective", meaning: "Wet" },
  { word: "quelithak", pos: "Adjective", meaning: "Short" },
  { word: "faerondiv", pos: "Adjective", meaning: "Wide" },
  { word: "ilduvalen", pos: "Adjective", meaning: "Narrow" },
  { word: "threnovar", pos: "Adjective", meaning: "Deep" },
  { word: "vurnaelithak", pos: "Adjective", meaning: "Shallow" },
  { word: "thalvornixak", pos: "Adjective", meaning: "Heavy" },
  { word: "brevakindrak", pos: "Adjective", meaning: "Light (weight)" },
  { word: "quelornivixak", pos: "Adjective", meaning: "Soft" },
  { word: "drenvaekivith", pos: "Adjective", meaning: "Hard" },
  { word: "ilvornivixak", pos: "Adjective", meaning: "Thick" },
  { word: "solmaekivixak", pos: "Adjective", meaning: "Thin" },
  { word: "faervonivixak", pos: "Adjective", meaning: "Round" },
  { word: "thalvoraxivixak", pos: "Adjective", meaning: "Flat" },
  { word: "brevonivaekixak", pos: "Adjective", meaning: "Curved" },
  { word: "quelvoraxivith", pos: "Adjective", meaning: "Pointed" },
  { word: "drenvaekivixal", pos: "Adjective", meaning: "New" },
  { word: "ilvakendrixivak", pos: "Adjective", meaning: "Old" },
  { word: "vornaelixak", pos: "Adjective", meaning: "Young" },
  { word: "threnivakixak", pos: "Adjective", meaning: "Rich" },
  { word: "quelvoraxivixak", pos: "Adjective", meaning: "Poor" },
  { word: "drenvaelixivak", pos: "Adjective", meaning: "Free" },
  { word: "ilvornivixivak", pos: "Adjective", meaning: "Bound" },
  { word: "solmaekivixivak", pos: "Adjective", meaning: "Living" },
  { word: "faervonivixivak", pos: "Adjective", meaning: "Dead" },
  { word: "thalvoraxivixivak", pos: "Adjective", meaning: "Sacred" },
  { word: "brevonivaekixivak", pos: "Adjective", meaning: "Cursed" },
  { word: "quelvoraxivixivak", pos: "Adjective", meaning: "Pure" },
  { word: "drenvakivixivak", pos: "Adjective", meaning: "Corrupt" },
  { word: "ilvakendrivixivak", pos: "Adjective", meaning: "Whole" },
  { word: "vurnaelivixivak", pos: "Adjective", meaning: "Broken" },
  { word: "thalvornivixivak", pos: "Adjective", meaning: "Open" },
  { word: "brevakivixivak", pos: "Adjective", meaning: "Closed" },
  { word: "quelornivixivak", pos: "Adjective", meaning: "Empty" },
  { word: "drenvaekivixivak", pos: "Adjective", meaning: "Full" },
  { word: "ilvornaevixivak", pos: "Adjective", meaning: "Lost" },
  { word: "solmaekivixivak", pos: "Adjective", meaning: "Found" },
  { word: "faervonivixivak", pos: "Adjective", meaning: "Hidden" },
  { word: "thalvoraxivixivak", pos: "Adjective", meaning: "Revealed" },
  { word: "brevonivaekixivak", pos: "Adjective", meaning: "Eternal" },
  { word: "quelvoraxivixivak", pos: "Adjective", meaning: "Fleeting" },
  { word: "drenvakivixivak", pos: "Adjective", meaning: "Fierce" },
  { word: "ilvakendrixivak", pos: "Adjective", meaning: "Gentle" },
  { word: "vurnaelixivak", pos: "Adjective", meaning: "Hungry" },
  { word: "thalvornivak", pos: "Adjective", meaning: "Thirsty" },
  { word: "brevakixivak", pos: "Adjective", meaning: "Tired" },
  { word: "quelornivak", pos: "Adjective", meaning: "Awake" },
  { word: "drenvaekivak", pos: "Adjective", meaning: "Asleep" },
  { word: "ilvornivak", pos: "Adjective", meaning: "Loyal" },
  { word: "solmaekivak", pos: "Adjective", meaning: "Treacherous" },
  { word: "faervonivak", pos: "Adjective", meaning: "Mysterious" },
  { word: "thalvoraxivak", pos: "Adjective", meaning: "Clear" },
  { word: "brevonivak", pos: "Adjective", meaning: "Cloudy" },
  { word: "quelvoraxivak", pos: "Adjective", meaning: "Stormy" },
  { word: "drenvakivak", pos: "Adjective", meaning: "Calm (weather)" },
  { word: "ilvakendrivak", pos: "Adjective", meaning: "Warm" },
  { word: "vurnaelivak", pos: "Adjective", meaning: "Freezing" },
  { word: "thalvornivaxak", pos: "Adjective", meaning: "Blazing" },
  { word: "brevakivaxak", pos: "Adjective", meaning: "Faded" },
  { word: "quelornivaxak", pos: "Adjective", meaning: "Vivid" },
  { word: "drenvakivaxak", pos: "Adjective", meaning: "Dull" },
  { word: "ilvornivaxak", pos: "Adjective", meaning: "Glowing" },
  { word: "solmaekivaxak", pos: "Adjective", meaning: "Shimmering" },
  { word: "faervonivaxak", pos: "Adjective", meaning: "Sparkling" },
  { word: "thalvoraxivaxak", pos: "Adjective", meaning: "Dim" },
  { word: "brevonivaekixaxak", pos: "Adjective", meaning: "Vast" },
  { word: "quelvoraxivaxak", pos: "Adjective", meaning: "Tiny" },
  { word: "drenvakivaxivak", pos: "Adjective", meaning: "Invisible" },
  { word: "ilvakendrixaxak", pos: "Adjective", meaning: "Transparent" },

  // ── VERBS ────────────────────────────────────────────────────────────────
  { word: "vuraen", pos: "Verb", meaning: "To run" },
  { word: "thivaelon", pos: "Verb", meaning: "To swim" },
  { word: "quelornen", pos: "Verb", meaning: "To speak" },
  { word: "orvakenth", pos: "Verb", meaning: "To sleep" },
  { word: "caldruvak", pos: "Verb", meaning: "To eat" },
  { word: "selmothen", pos: "Verb", meaning: "To drink" },
  { word: "drenvaelon", pos: "Verb", meaning: "To build" },
  { word: "yuvornaen", pos: "Verb", meaning: "To hunt" },
  { word: "solmirend", pos: "Verb", meaning: "To heal" },
  { word: "faevrathen", pos: "Verb", meaning: "To fly" },
  { word: "thornvaeld", pos: "Verb", meaning: "To climb" },
  { word: "meldruvak", pos: "Verb", meaning: "To sing" },
  { word: "caelvornen", pos: "Verb", meaning: "To fight" },
  { word: "brevakend", pos: "Verb", meaning: "To laugh" },
  { word: "uldmirend", pos: "Verb", meaning: "To cry" },
  { word: "threnovalon", pos: "Verb", meaning: "To think" },
  { word: "quelvaenon", pos: "Verb", meaning: "To dream" },
  { word: "orveldrund", pos: "Verb", meaning: "To remember" },
  { word: "salmaetha", pos: "Verb", meaning: "To forget" },
  { word: "brevithal", pos: "Verb", meaning: "To love" },
  { word: "voraelund", pos: "Verb", meaning: "To see" },
  { word: "thimralven", pos: "Verb", meaning: "To hear" },
  { word: "caeldrixend", pos: "Verb", meaning: "To touch" },
  { word: "uvithaelend", pos: "Verb", meaning: "To feel" },
  { word: "solmethixon", pos: "Verb", meaning: "To breathe" },
  { word: "drenvornixa", pos: "Verb", meaning: "To grow" },
  { word: "quelvorilund", pos: "Verb", meaning: "To fall" },
  { word: "faerathond", pos: "Verb", meaning: "To rise" },
  { word: "ildrakonel", pos: "Verb", meaning: "To hide" },
  { word: "thornvaexond", pos: "Verb", meaning: "To seek" },
  { word: "meldronaeld", pos: "Verb", meaning: "To create" },
  { word: "caervindralon", pos: "Verb", meaning: "To destroy" },
  { word: "brevorneld", pos: "Verb", meaning: "To protect" },
  { word: "uldvaraenov", pos: "Verb", meaning: "To flee" },
  { word: "thalvornaelith", pos: "Verb", meaning: "To follow" },
  { word: "quelithenov", pos: "Verb", meaning: "To give" },
  { word: "orveldrukend", pos: "Verb", meaning: "To take" },
  { word: "salmirethov", pos: "Verb", meaning: "To open" },
  { word: "faevitharex", pos: "Verb", meaning: "To close" },
  { word: "drenmethoxend", pos: "Verb", meaning: "To return" },
  { word: "vurnaelivond", pos: "Verb", meaning: "To walk" },
  { word: "thalvornivond", pos: "Verb", meaning: "To jump" },
  { word: "brevakivond", pos: "Verb", meaning: "To dance" },
  { word: "quelornivond", pos: "Verb", meaning: "To pray" },
  { word: "drenvaekivond", pos: "Verb", meaning: "To write" },
  { word: "ilvornivond", pos: "Verb", meaning: "To read" },
  { word: "solmaekivond", pos: "Verb", meaning: "To draw" },
  { word: "faervonivond", pos: "Verb", meaning: "To paint" },
  { word: "thalvoraxivond", pos: "Verb", meaning: "To carve" },
  { word: "brevonivaekivond", pos: "Verb", meaning: "To forge" },
  { word: "quelvoraxivond", pos: "Verb", meaning: "To weave" },
  { word: "drenvakivond", pos: "Verb", meaning: "To sew" },
  { word: "ilvakendrivond", pos: "Verb", meaning: "To cook" },
  { word: "vurnaelixond", pos: "Verb", meaning: "To bake" },
  { word: "thalvornivaxond", pos: "Verb", meaning: "To brew" },
  { word: "brevakivaxond", pos: "Verb", meaning: "To harvest" },
  { word: "quelornivaxond", pos: "Verb", meaning: "To plant" },
  { word: "drenvakivaxond", pos: "Verb", meaning: "To dig" },
  { word: "ilvornivaxond", pos: "Verb", meaning: "To cut" },
  { word: "solmaekivaxond", pos: "Verb", meaning: "To break" },
  { word: "faervonivaxond", pos: "Verb", meaning: "To mend" },
  { word: "thalvoraxivaxond", pos: "Verb", meaning: "To carry" },
  { word: "brevonivaekixaxond", pos: "Verb", meaning: "To throw" },
  { word: "quelvoraxivaxond", pos: "Verb", meaning: "To catch" },
  { word: "drenvakivaxivond", pos: "Verb", meaning: "To push" },
  { word: "ilvakendrixaxond", pos: "Verb", meaning: "To pull" },
  { word: "vurnaelivaxond", pos: "Verb", meaning: "To lift" },
  { word: "thalvornivaxivond", pos: "Verb", meaning: "To drop" },
  { word: "brevakivaxivond", pos: "Verb", meaning: "To tie" },
  { word: "quelornivaxivond", pos: "Verb", meaning: "To untie" },
  { word: "drenvaekivaxivond", pos: "Verb", meaning: "To bind" },
  { word: "ilvornivaxivond", pos: "Verb", meaning: "To release" },
  { word: "solmaekivaxivond", pos: "Verb", meaning: "To choose" },
  { word: "faervonivaxivond", pos: "Verb", meaning: "To refuse" },
  { word: "thalvoraxivaxivond", pos: "Verb", meaning: "To agree" },
  { word: "brevonivaekixaxivond", pos: "Verb", meaning: "To argue" },
  { word: "quelvoraxivaxivond", pos: "Verb", meaning: "To whisper" },
  { word: "drenvakivaxivond", pos: "Verb", meaning: "To shout" },
  { word: "ilvakendrixaxivond", pos: "Verb", meaning: "To command" },
  { word: "vurnaelivaxivond", pos: "Verb", meaning: "To obey" },
  { word: "thalvornivaxivaxond", pos: "Verb", meaning: "To betray" },
  { word: "brevakivaxivaxond", pos: "Verb", meaning: "To trust" },
  { word: "quelornivaxivaxond", pos: "Verb", meaning: "To doubt" },
  { word: "drenvakivaxivaxond", pos: "Verb", meaning: "To know" },
  { word: "ilvornivaxivaxond", pos: "Verb", meaning: "To learn" },
  { word: "solmaekivaxivaxond", pos: "Verb", meaning: "To teach" },
  { word: "faervonivaxivaxond", pos: "Verb", meaning: "To warn" },
  { word: "thalvoraxivaxivaxond", pos: "Verb", meaning: "To bless" },
  { word: "brevonivaekixaxivaxond", pos: "Verb", meaning: "To curse" },
  { word: "quelvoraxivaxivaxond", pos: "Verb", meaning: "To awaken" },
  { word: "drenvakivaxivaxond", pos: "Verb", meaning: "To wander" },
  { word: "ilvakendrixaxivaxond", pos: "Verb", meaning: "To conquer" },
  { word: "vurnaelivaxivaxond", pos: "Verb", meaning: "To surrender" },
  { word: "thalvornivaxivaxivond", pos: "Verb", meaning: "To sacrifice" },
  { word: "brevakivaxivaxivond", pos: "Verb", meaning: "To forgive" },
  { word: "quelornivaxivaxivond", pos: "Verb", meaning: "To punish" },
  { word: "drenvakivaxivaxivond", pos: "Verb", meaning: "To reward" },
  { word: "ilvornivaxivaxivond", pos: "Verb", meaning: "To mourn" },
  { word: "solmaekivaxivaxivond", pos: "Verb", meaning: "To celebrate" },
  { word: "faervonivaxivaxivond", pos: "Verb", meaning: "To transform" },
  { word: "thalvoraxivaxivaxivond", pos: "Verb", meaning: "To illuminate" },
  { word: "brevonivaekixaxivaxivond", pos: "Verb", meaning: "To vanish" },
  { word: "quelvoraxivaxivaxivond", pos: "Verb", meaning: "To summon" },
  { word: "drenvakivaxivaxivond", pos: "Verb", meaning: "To banish" },
  { word: "ilvakendrixaxivaxivond", pos: "Verb", meaning: "To enchant" },
  { word: "vurnaelivaxivaxivond", pos: "Verb", meaning: "To deceive" },
  { word: "thalvornivaxivaxivaxond", pos: "Verb", meaning: "To reveal" },
  { word: "brevakivaxivaxivaxond", pos: "Verb", meaning: "To endure" },
  { word: "quelornivaxivaxivaxond", pos: "Verb", meaning: "To perish" },

  // ── PRONOUNS / GRAMMAR WORDS ─────────────────────────────────────────────
  { word: "vel", pos: "Pronoun", meaning: "I / Me" },
  { word: "thorn", pos: "Pronoun", meaning: "You (singular)" },
  { word: "queliv", pos: "Pronoun", meaning: "He / Him" },
  { word: "drenvae", pos: "Pronoun", meaning: "She / Her" },
  { word: "ilvorn", pos: "Pronoun", meaning: "It" },
  { word: "velvorn", pos: "Pronoun", meaning: "We / Us" },
  { word: "thornvael", pos: "Pronoun", meaning: "You (plural)" },
  { word: "queldriv", pos: "Pronoun", meaning: "They / Them" },
  { word: "aelvor", pos: "Pronoun", meaning: "This" },
  { word: "threnval", pos: "Pronoun", meaning: "That" },
  { word: "solvaek", pos: "Pronoun", meaning: "Which" },
  { word: "faervon", pos: "Pronoun", meaning: "Who" },
  { word: "drenvaek", pos: "Pronoun", meaning: "What" },
  { word: "ilvakend", pos: "Pronoun", meaning: "Where" },
  { word: "vurnaeli", pos: "Pronoun", meaning: "When" },
  { word: "thalvorn", pos: "Pronoun", meaning: "Why" },
  { word: "brevaki", pos: "Pronoun", meaning: "How" },

  // ── PREPOSITIONS / CONJUNCTIONS ──────────────────────────────────────────
  { word: "ven", pos: "Preposition", meaning: "In / Inside" },
  { word: "thrak", pos: "Preposition", meaning: "On / Upon" },
  { word: "quelath", pos: "Preposition", meaning: "Under / Beneath" },
  { word: "drev", pos: "Preposition", meaning: "Over / Above" },
  { word: "ilvo", pos: "Preposition", meaning: "Before" },
  { word: "solmae", pos: "Preposition", meaning: "After" },
  { word: "faern", pos: "Preposition", meaning: "Near / Beside" },
  { word: "thalvo", pos: "Preposition", meaning: "Far from" },
  { word: "breva", pos: "Preposition", meaning: "Between" },
  { word: "quelorn", pos: "Preposition", meaning: "Through" },
  { word: "drenva", pos: "Preposition", meaning: "Around" },
  { word: "ilva", pos: "Preposition", meaning: "Toward" },
  { word: "vurna", pos: "Preposition", meaning: "Away from" },
  { word: "ak", pos: "Conjunction", meaning: "And" },
  { word: "vel", pos: "Conjunction", meaning: "Or" },
  { word: "neth", pos: "Conjunction", meaning: "But" },
  { word: "threk", pos: "Conjunction", meaning: "Because" },
  { word: "queliv", pos: "Conjunction", meaning: "If" },
  { word: "drevon", pos: "Conjunction", meaning: "So / Therefore" },
  { word: "ilvorn", pos: "Conjunction", meaning: "Although" },
  { word: "solvaek", pos: "Conjunction", meaning: "While" },
  { word: "faernoth", pos: "Conjunction", meaning: "Until" },
  { word: "thalkiv", pos: "Conjunction", meaning: "Unless" },

  // ── INTERJECTIONS ────────────────────────────────────────────────────────
  { word: "vael", pos: "Interjection", meaning: "Yes" },
  { word: "neth", pos: "Interjection", meaning: "No" },
  { word: "aevorn", pos: "Interjection", meaning: "Hello / Greetings" },
  { word: "solketh", pos: "Interjection", meaning: "Farewell" },
  { word: "queldrae", pos: "Interjection", meaning: "Thank you" },
  { word: "threnvik", pos: "Interjection", meaning: "Please" },
  { word: "ilvorn", pos: "Interjection", meaning: "Sorry / Forgive me" },
  { word: "caldru", pos: "Interjection", meaning: "Help!" },
  { word: "brevak", pos: "Interjection", meaning: "Beware!" },
  { word: "vornaek", pos: "Interjection", meaning: "Victory!" },
  { word: "drenvithe", pos: "Interjection", meaning: "Halt! / Stop!" },
];

module.exports = lexicon;
