// Aureon Language Lexicon — Voltic Apex Archive
const LEXICON = [
  // NOUNS — Nature
  { aureon: "vorael", pos: "Noun", meaning: "Sun" },
  { aureon: "thiveln", pos: "Noun", meaning: "Water" },
  { aureon: "caendor", pos: "Noun", meaning: "Mountain" },
  { aureon: "uviraek", pos: "Noun", meaning: "Fire" },
  { aureon: "solmeth", pos: "Noun", meaning: "Wind" },
  { aureon: "dravenil", pos: "Noun", meaning: "Tree" },
  { aureon: "quelithar", pos: "Noun", meaning: "Stone" },
  { aureon: "faerond", pos: "Noun", meaning: "Sky" },
  { aureon: "ilduvok", pos: "Noun", meaning: "Sea" },
  { aureon: "threnox", pos: "Noun", meaning: "Soil / Earth" },
  { aureon: "olvaren", pos: "Noun", meaning: "Moon" },
  { aureon: "zephkion", pos: "Noun", meaning: "Star" },
  { aureon: "brumathal", pos: "Noun", meaning: "Cloud" },
  { aureon: "oriveld", pos: "Noun", meaning: "Rain" },
  { aureon: "galnethor", pos: "Noun", meaning: "Snow" },
  { aureon: "yuvraek", pos: "Noun", meaning: "Ice" },
  { aureon: "draemoliv", pos: "Noun", meaning: "Flower" },
  { aureon: "sevionath", pos: "Noun", meaning: "Leaf" },
  { aureon: "corvelith", pos: "Noun", meaning: "Root" },
  { aureon: "thuriaen", pos: "Noun", meaning: "Seed" },
  { aureon: "elvornath", pos: "Noun", meaning: "Fruit" },
  { aureon: "nithaelon", pos: "Noun", meaning: "River" },
  { aureon: "quelvaren", pos: "Noun", meaning: "Lake" },
  { aureon: "orventh", pos: "Noun", meaning: "Cave" },
  { aureon: "salmireth", pos: "Noun", meaning: "Desert" },
  { aureon: "fendraxon", pos: "Noun", meaning: "Forest" },
  { aureon: "vaelunith", pos: "Noun", meaning: "Island" },
  { aureon: "throvalon", pos: "Noun", meaning: "Valley" },
  { aureon: "caeldunath", pos: "Noun", meaning: "Cliff" },
  { aureon: "mornithelon", pos: "Noun", meaning: "Fog" },
  // Time & Seasons
  { aureon: "brevaelon", pos: "Noun", meaning: "Dawn" },
  { aureon: "solkethiv", pos: "Noun", meaning: "Dusk" },
  { aureon: "veldronis", pos: "Noun", meaning: "Night" },
  { aureon: "auremnil", pos: "Noun", meaning: "Day" },
  { aureon: "thyronaeth", pos: "Noun", meaning: "Year" },
  { aureon: "fenvalis", pos: "Noun", meaning: "Season" },
  { aureon: "uldrathen", pos: "Noun", meaning: "Spring" },
  { aureon: "caervonith", pos: "Noun", meaning: "Summer" },
  { aureon: "melvithar", pos: "Noun", meaning: "Autumn" },
  { aureon: "drothynael", pos: "Noun", meaning: "Winter" },
  { aureon: "voraenil", pos: "Noun", meaning: "Morning" },
  { aureon: "thimranel", pos: "Noun", meaning: "Afternoon" },
  { aureon: "caeldorixa", pos: "Noun", meaning: "Evening" },
  { aureon: "solmeritha", pos: "Noun", meaning: "Hour" },
  { aureon: "drenvithor", pos: "Noun", meaning: "Minute" },
  { aureon: "quelvorix", pos: "Noun", meaning: "Second" },
  { aureon: "faerathor", pos: "Noun", meaning: "Week" },
  { aureon: "ildmethorn", pos: "Noun", meaning: "Month" },
  { aureon: "thornaelond", pos: "Noun", meaning: "Century" },
  // Animals
  { aureon: "vurkaelon", pos: "Noun", meaning: "Wolf" },
  { aureon: "thivronath", pos: "Noun", meaning: "Eagle" },
  { aureon: "quelmarev", pos: "Noun", meaning: "Deer" },
  { aureon: "orvithek", pos: "Noun", meaning: "Fish" },
  { aureon: "caeldrakis", pos: "Noun", meaning: "Serpent" },
  { aureon: "yuvmirak", pos: "Noun", meaning: "Bear" },
  { aureon: "selnothar", pos: "Noun", meaning: "Fox" },
  { aureon: "brevkinel", pos: "Noun", meaning: "Rabbit" },
  { aureon: "drumathok", pos: "Noun", meaning: "Horse" },
  { aureon: "thornvelis", pos: "Noun", meaning: "Cat" },
  // People & Society
  { aureon: "aelvorith", pos: "Noun", meaning: "Person" },
  { aureon: "threndalon", pos: "Noun", meaning: "Child" },
  { aureon: "quelorneth", pos: "Noun", meaning: "Elder" },
  { aureon: "vurmethis", pos: "Noun", meaning: "Warrior" },
  { aureon: "solvaneith", pos: "Noun", meaning: "Healer" },
  { aureon: "faendrixal", pos: "Noun", meaning: "Merchant" },
  { aureon: "ildrakoth", pos: "Noun", meaning: "Scholar" },
  { aureon: "caervelith", pos: "Noun", meaning: "King" },
  { aureon: "mornaeliv", pos: "Noun", meaning: "Queen" },
  { aureon: "brevithon", pos: "Noun", meaning: "Friend" },
  // Objects & Places
  { aureon: "vurmithon", pos: "Noun", meaning: "Sword" },
  { aureon: "thivaelon", pos: "Noun", meaning: "Shield" },
  { aureon: "queldrakis", pos: "Noun", meaning: "Bow" },
  { aureon: "orvithaeld", pos: "Noun", meaning: "Spear" },
  { aureon: "caldrunath", pos: "Noun", meaning: "Armor" },
  { aureon: "selmothix", pos: "Noun", meaning: "Crown" },
  { aureon: "drenvaelithe", pos: "Noun", meaning: "Throne" },
  { aureon: "yuvornithen", pos: "Noun", meaning: "Castle" },
  { aureon: "solmiraeld", pos: "Noun", meaning: "Tower" },
  { aureon: "faevraelith", pos: "Noun", meaning: "Bridge" },
  { aureon: "thornvaelond", pos: "Noun", meaning: "Road" },
  { aureon: "meldruvik", pos: "Noun", meaning: "Village" },
  { aureon: "caelvorith", pos: "Noun", meaning: "City" },
  { aureon: "brevakenth", pos: "Noun", meaning: "Market" },
  { aureon: "uldmirenix", pos: "Noun", meaning: "Temple" },
  { aureon: "threnovalith", pos: "Noun", meaning: "Library" },
  { aureon: "quelvaenith", pos: "Noun", meaning: "Garden" },
  { aureon: "orveldrumath", pos: "Noun", meaning: "Forge" },
  { aureon: "salmaetha", pos: "Noun", meaning: "Ship" },
  { aureon: "brevithalith", pos: "Noun", meaning: "Scroll" },
  // Abstract concepts
  { aureon: "voraenth", pos: "Noun", meaning: "Light" },
  { aureon: "thimraken", pos: "Noun", meaning: "Shadow" },
  { aureon: "caeldorith", pos: "Noun", meaning: "Hope" },
  { aureon: "uvithalend", pos: "Noun", meaning: "Despair" },
  { aureon: "solmerith", pos: "Noun", meaning: "Courage" },
  { aureon: "drenvithaeld", pos: "Noun", meaning: "Honor" },
  { aureon: "quelvorith", pos: "Noun", meaning: "Truth" },
  { aureon: "faerathorix", pos: "Noun", meaning: "Beauty" },
  { aureon: "ildmethon", pos: "Noun", meaning: "Fear" },
  { aureon: "thornaelix", pos: "Noun", meaning: "Memory" },
  { aureon: "meldrakond", pos: "Noun", meaning: "Joy" },
  { aureon: "caervindrak", pos: "Noun", meaning: "Sorrow" },
  { aureon: "brevornith", pos: "Noun", meaning: "Peace" },
  { aureon: "uldvarael", pos: "Noun", meaning: "War" },
  { aureon: "thalvornixa", pos: "Noun", meaning: "Justice" },
  { aureon: "quelithenoth", pos: "Noun", meaning: "Mercy" },
  { aureon: "orveldraki", pos: "Noun", meaning: "Power" },
  { aureon: "salmirenth", pos: "Noun", meaning: "Knowledge" },
  { aureon: "faevithalon", pos: "Noun", meaning: "Music" },
  { aureon: "drenmethixal", pos: "Noun", meaning: "Silence" },
  // Food
  { aureon: "meldroneth", pos: "Noun", meaning: "Bread" },
  { aureon: "caervinalith", pos: "Noun", meaning: "Meat" },
  { aureon: "brevakendral", pos: "Noun", meaning: "Herb" },
  { aureon: "uldmirithex", pos: "Noun", meaning: "Honey" },
  { aureon: "thalvorenax", pos: "Noun", meaning: "Salt" },
  { aureon: "quelithendor", pos: "Noun", meaning: "Grain" },
  { aureon: "orveldruxith", pos: "Noun", meaning: "Mushroom" },
  { aureon: "salmirexond", pos: "Noun", meaning: "Berry" },
  { aureon: "faevitharxen", pos: "Noun", meaning: "Nut" },
  { aureon: "drenmethoxal", pos: "Noun", meaning: "Root vegetable" },
  // Emotions
  { aureon: "meldrakona", pos: "Noun", meaning: "Anger" },
  { aureon: "caervindral", pos: "Noun", meaning: "Surprise" },
  { aureon: "brevornell", pos: "Noun", meaning: "Excitement" },
  { aureon: "uldvaraex", pos: "Noun", meaning: "Anxiety" },
  { aureon: "thalvornelos", pos: "Noun", meaning: "Confidence" },
  { aureon: "quelithenos", pos: "Noun", meaning: "Loneliness" },
  { aureon: "orveldraken", pos: "Noun", meaning: "Gratitude" },
  { aureon: "salmaethix", pos: "Noun", meaning: "Curiosity" },
  { aureon: "faevithalond", pos: "Noun", meaning: "Pride" },
  { aureon: "drenmethora", pos: "Noun", meaning: "Shame" },
  // Phenomena
  { aureon: "voraelik", pos: "Noun", meaning: "Horizon" },
  { aureon: "thimralven", pos: "Noun", meaning: "Tide" },
  { aureon: "caeldrixoth", pos: "Noun", meaning: "Echo" },
  { aureon: "uvithaelorn", pos: "Noun", meaning: "Flame" },
  { aureon: "solmethixal", pos: "Noun", meaning: "Whisper" },
  { aureon: "drenvorneth", pos: "Noun", meaning: "Thunder" },
  { aureon: "quelvorilond", pos: "Noun", meaning: "Lightning" },
  { aureon: "faerathorex", pos: "Noun", meaning: "Rainbow" },
  { aureon: "ildrakonen", pos: "Noun", meaning: "Mist" },
  { aureon: "thornvaexith", pos: "Noun", meaning: "Dust" },
  // Materials
  { aureon: "thalvorenaxil", pos: "Noun", meaning: "Iron" },
  { aureon: "quelithendar", pos: "Noun", meaning: "Gold" },
  { aureon: "orveldruxithe", pos: "Noun", meaning: "Silver" },
  { aureon: "faevitharxeld", pos: "Noun", meaning: "Ivory" },
  { aureon: "drenmethoxen", pos: "Noun", meaning: "Coal" },
  // Body
  { aureon: "voraevith", pos: "Noun", meaning: "Eye" },
  { aureon: "thimralthe", pos: "Noun", meaning: "Ear" },
  { aureon: "caeldrixon", pos: "Noun", meaning: "Hand" },
  { aureon: "uvithaeliv", pos: "Noun", meaning: "Foot" },
  { aureon: "solmethixor", pos: "Noun", meaning: "Mouth" },
  { aureon: "drenvorniv", pos: "Noun", meaning: "Nose" },
  { aureon: "quelvorilath", pos: "Noun", meaning: "Head" },
  { aureon: "faerathoril", pos: "Noun", meaning: "Heart" },
  { aureon: "ildrakoren", pos: "Noun", meaning: "Back" },
  { aureon: "thornvaexal", pos: "Noun", meaning: "Arm" },
  { aureon: "voraelith", pos: "Noun", meaning: "Leg" },
  { aureon: "thivelnath", pos: "Noun", meaning: "Finger" },
  { aureon: "caendoriv", pos: "Noun", meaning: "Tooth" },
  { aureon: "uviraekond", pos: "Noun", meaning: "Tongue" },
  { aureon: "solmethend", pos: "Noun", meaning: "Breath" },
  // NUMBERS
  { aureon: "vorae", pos: "Number", meaning: "One" },
  { aureon: "thimen", pos: "Number", meaning: "Two" },
  { aureon: "quelda", pos: "Number", meaning: "Three" },
  { aureon: "orvik", pos: "Number", meaning: "Four" },
  { aureon: "caldur", pos: "Number", meaning: "Five" },
  { aureon: "selmon", pos: "Number", meaning: "Six" },
  { aureon: "drenval", pos: "Number", meaning: "Seven" },
  { aureon: "yuvrek", pos: "Number", meaning: "Eight" },
  { aureon: "solmae", pos: "Number", meaning: "Nine" },
  { aureon: "faevith", pos: "Number", meaning: "Ten" },
  // ADJECTIVES — Colors
  { aureon: "vurmaeth", pos: "Adjective", meaning: "Red" },
  { aureon: "thiventh", pos: "Adjective", meaning: "Blue" },
  { aureon: "quelvarith", pos: "Adjective", meaning: "Green" },
  { aureon: "orviken", pos: "Adjective", meaning: "Yellow" },
  { aureon: "caldrumith", pos: "Adjective", meaning: "Orange" },
  { aureon: "selmiren", pos: "Adjective", meaning: "Purple" },
  { aureon: "drenvalix", pos: "Adjective", meaning: "White" },
  { aureon: "yuvornaeth", pos: "Adjective", meaning: "Black" },
  { aureon: "solmaevith", pos: "Adjective", meaning: "Grey" },
  { aureon: "faerathun", pos: "Adjective", meaning: "Brown" },
  // Descriptive adjectives
  { aureon: "voraen", pos: "Adjective", meaning: "Bright" },
  { aureon: "thimrak", pos: "Adjective", meaning: "Cold" },
  { aureon: "caeldorak", pos: "Adjective", meaning: "Tall" },
  { aureon: "uvithaeld", pos: "Adjective", meaning: "Hot" },
  { aureon: "solmeriv", pos: "Adjective", meaning: "Fast" },
  { aureon: "drenvithael", pos: "Adjective", meaning: "Strong" },
  { aureon: "quelvornixa", pos: "Adjective", meaning: "Wise" },
  { aureon: "faerathen", pos: "Adjective", meaning: "Beautiful" },
  { aureon: "ildmethak", pos: "Adjective", meaning: "Dark" },
  { aureon: "thornaelon", pos: "Adjective", meaning: "Ancient" },
  { aureon: "meldrakiv", pos: "Adjective", meaning: "Small" },
  { aureon: "caervinath", pos: "Adjective", meaning: "Large" },
  { aureon: "brevornath", pos: "Adjective", meaning: "Happy" },
  { aureon: "uldvarith", pos: "Adjective", meaning: "Sad" },
  { aureon: "thalvornil", pos: "Adjective", meaning: "Brave" },
  { aureon: "quelithend", pos: "Adjective", meaning: "Kind" },
  { aureon: "orveldrak", pos: "Adjective", meaning: "Cruel" },
  { aureon: "salmiren", pos: "Adjective", meaning: "Silent" },
  { aureon: "faevithald", pos: "Adjective", meaning: "Loud" },
  { aureon: "drenmethiv", pos: "Adjective", meaning: "Sharp" },
  { aureon: "vurmaetha", pos: "Adjective", meaning: "Hollow" },
  { aureon: "thivelniv", pos: "Adjective", meaning: "Smooth" },
  { aureon: "caendorix", pos: "Adjective", meaning: "Rough" },
  { aureon: "uviraekil", pos: "Adjective", meaning: "Dry" },
  { aureon: "solmethal", pos: "Adjective", meaning: "Wet" },
  { aureon: "quelithak", pos: "Adjective", meaning: "Short" },
  { aureon: "faerondiv", pos: "Adjective", meaning: "Wide" },
  { aureon: "ilduvalen", pos: "Adjective", meaning: "Narrow" },
  { aureon: "threnovar", pos: "Adjective", meaning: "Deep" },
  // VERBS
  { aureon: "vuraen", pos: "Verb", meaning: "To run" },
  { aureon: "quelornen", pos: "Verb", meaning: "To speak" },
  { aureon: "orvakenth", pos: "Verb", meaning: "To sleep" },
  { aureon: "caldruvak", pos: "Verb", meaning: "To eat" },
  { aureon: "selmothen", pos: "Verb", meaning: "To drink" },
  { aureon: "drenvaelon", pos: "Verb", meaning: "To build" },
  { aureon: "yuvornaen", pos: "Verb", meaning: "To hunt" },
  { aureon: "solmirend", pos: "Verb", meaning: "To heal" },
  { aureon: "faevrathen", pos: "Verb", meaning: "To fly" },
  { aureon: "thornvaeld", pos: "Verb", meaning: "To climb" },
  { aureon: "meldruvak", pos: "Verb", meaning: "To sing" },
  { aureon: "caelvornen", pos: "Verb", meaning: "To fight" },
  { aureon: "brevakend", pos: "Verb", meaning: "To laugh" },
  { aureon: "uldmirend", pos: "Verb", meaning: "To cry" },
  { aureon: "threnovalon", pos: "Verb", meaning: "To think" },
  { aureon: "quelvaenon", pos: "Verb", meaning: "To dream" },
  { aureon: "orveldrund", pos: "Verb", meaning: "To remember" },
  { aureon: "brevithal", pos: "Verb", meaning: "To love" },
  { aureon: "voraelund", pos: "Verb", meaning: "To see" },
  { aureon: "caeldrixend", pos: "Verb", meaning: "To touch" },
  { aureon: "uvithaelend", pos: "Verb", meaning: "To feel" },
  { aureon: "solmethixon", pos: "Verb", meaning: "To breathe" },
  { aureon: "drenvornixa", pos: "Verb", meaning: "To grow" },
  { aureon: "quelvorilund", pos: "Verb", meaning: "To fall" },
  { aureon: "faerathond", pos: "Verb", meaning: "To rise" },
  { aureon: "ildrakonel", pos: "Verb", meaning: "To hide" },
  { aureon: "thornvaexond", pos: "Verb", meaning: "To seek" },
  { aureon: "meldronaeld", pos: "Verb", meaning: "To create" },
  { aureon: "caervindralon", pos: "Verb", meaning: "To destroy" },
  { aureon: "brevorneld", pos: "Verb", meaning: "To protect" },
  { aureon: "uldvaraenov", pos: "Verb", meaning: "To flee" },
  { aureon: "thalvornaelith", pos: "Verb", meaning: "To follow" },
  { aureon: "quelithenov", pos: "Verb", meaning: "To give" },
  { aureon: "orveldrukend", pos: "Verb", meaning: "To take" },
  { aureon: "salmirethov", pos: "Verb", meaning: "To open" },
  { aureon: "faevitharex", pos: "Verb", meaning: "To close" },
  { aureon: "drenmethoxend", pos: "Verb", meaning: "To return" },
  { aureon: "thivaelon", pos: "Verb", meaning: "To swim" },
  { aureon: "thimralven", pos: "Verb", meaning: "To hear" },
  { aureon: "salmaetha", pos: "Verb", meaning: "To forget" },
];
